DELETE https://0v56vgdalf.execute-api.us-east-1.amazonaws.com/dev/api/customers/{{userId}}
x-api-key: wXnvKbose91eG0STX4BHB5czspaK7kTn85XlRxVu
Content-Type: application/json

### Replace {{userId}} with an actual customer ID
