### Create Customer
POST {{baseUrl}}/api/customers
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "userId": "customer12345",
  "name": "Peter Parker",
  "email": "parker@example.com",
  "phone": "+1234567890",
  "availableCredit": 2000
}
