### Add Credit to Customer
@customerId = b28f41ae-ddaa-4cab-893f-0035452b89dd

POST {{baseUrl}}/api/customers/{{customerId}}/credit
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "amount": 500
}
